
void confADC(void){

	ADC_Init(LPC_ADC,200000);
	ADC_BurstCmd(LPC_ADC,ENABLE);
	ADC_IntConfig(LPC_ADC,ADC_ADINTEN0,ENABLE);
	ADC_IntConfig(LPC_ADC,ADC_ADGINTEN,DISABLE);
	ADC_ChannelCmd(LPC_ADC,ADC_CHANNEL_0,ENABLE);
	//NVIC_EnableIRQ(ADC_IRQn);

}
